language: java
dist: xenial
sudo: required
before_install:
- sudo apt update
- sudo apt install software-properties-common python-software-properties -y
- sudo apt-add-repository ppa:wpilib/toolchain -y && sudo add-apt-repository ppa:openjdk-r/ppa
  -y && sudo apt update
- sudo apt install default-jdk frc-toolchain -y
script: cd 2019Robot && chmod 777 gradlew && ./gradlew assemble
notifications:
  slack:
    secure: Xsu1OFiAMTlvZFBITq3kkfWp8Xuu1527+PnIRbiRwDxW60Wi9HOJyJScRXXj/rIONagWMC42jH7l211xFY40LMJKEAOw9/eVr4cnhd1QAo+C9pgKa2AjbMm9GuK2P63hQJG9tGRBXbvLwrGrJffkwiSXu01Og7ybWyUEQm4G6m8FodcibeQ/5FPCh/sz09k77SbTFY+OIo3sCJ1oZrEOwvem6o7sHnz/u28H1jiWhcGKBgurhwAiMuyI9inGzdZXs+f61kaeITGDgJR28SKT9P88+cjnA7/fFy2mONuuZefRx6+DqEHYE6MeuYOzKHFCvPQ4CJm5LbFJEM7/QfXmVXzDFXVcYBWj36jliC6WT08qpoKIobayfng2C+dFjfbgpV8/M16QRmJnzf1+WsvIp1vc/CqB6ihEzltso996Jb+nstF2QfUlQnVF2pSUuCXt+nXvFGUTL9IUWwjTk51AXB7pIsJAnafoucYSmF6TuETjTY+H/9g47pziyDJH1ZJe0aNfAle8kN0JLMH0KayUFCf8ZBBsLePuk5q/pmMSRpwML0QUly+zMgWo95zBiGIoM1Ulk0+1eX+F7IfVaFRDs+0e9SN4vghckaoeUmnh3QDgHALswC4JL1I6gnPvv4cbJiEcVOAJa8QE5UWmuU20scYMxeSc6kVjsT3+kbNPoCI=
